name: Test the code

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint_the_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "poetry"
      - run: poetry run python --version
      - run: poetry install
      - run: poetry run pytest
